# Generated by Django 4.2.7 on 2023-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='girl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('hair', models.CharField(max_length=20)),
                ('eyes', models.CharField(max_length=20)),
                ('form', models.CharField(max_length=20)),
                ('born', models.CharField(max_length=20)),
                ('habbits', models.TextField(max_length=254)),
            ],
        ),
    ]
