# Generated by Django 4.2.7 on 2024-03-07 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otBoys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='otBoysInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.CharField(max_length=20)),
                ('describe', models.TextField(max_length=254)),
                ('showtime', models.CharField(max_length=20)),
                ('habbits', models.TextField(max_length=254)),
                ('fromWhere', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=20)),
                ('special', models.CharField(max_length=20)),
                ('BGMlinks', models.CharField(max_length=20)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.otboys')),
            ],
        ),
    ]
